FROM python:3.11-slim
WORKDIR /opt/ml/code
COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt
COPY server ./server
COPY sagemaker/inference.py .
ENV SAGEMAKER_PROGRAM=inference.py
ENTRYPOINT ["python", "-m", "sagemaker_inference.server"]
CMD ["--model-dir", "/opt/ml/model"]