# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install -U "ultralytics>=8.3.237"

from huggingface_hub import login

# 3. Import and Load Model
from ultralytics import SAM
from huggingface_hub import hf_hub_download
import os
# Manually download the model
model_name = "sam3.pt"
if not os.path.exists(model_name):
    print(f"Downloading {model_name} from Hugging Face...")
    try:
        hf_hub_download(repo_id="facebook/sam3", filename=model_name, local_dir=".")
        print("Download complete.")
    except Exception as e:
        print(f"Failed to download model: {e}")
        print("Please ensure you have accepted the license at https://huggingface.co/facebook/sam3")
# Load the SAM 3 model
model = SAM(model_name)
model.info()

import requests
from PIL import Image
from io import BytesIO

# URL of a person wearing cargo pants
url = "https://media.istockphoto.com/id/175432675/photo/cargo-pants.jpg?s=612x612&w=0&k=20&c=N_lqg3n-aKzR0w0FwW5Xy94g5nJ5qE3q04660020114=" # Placeholder URL
# Using a stable image from ultralytics assets or similar is better, but this is a generic example
!wget -O sample.jpg "https://ultralytics.com/images/bus.jpg"

from ultralytics.models.sam import SAM3SemanticPredictor

# Initialize predictor with configuration
image_path = "test2.jpeg"
overrides = dict(
    conf=0.25,
    task="segment",
    mode="predict",
    model="sam3.pt",
    half=True,  # Use FP16 for faster inference
    save=True,
)
predictor = SAM3SemanticPredictor(overrides=overrides)

# Set image once for multiple queries
predictor.set_image(image_path)

# Query with multiple text prompts
results = predictor(text=['blazer'])


# Display results
for result in results:
    result.show()
# # Works with descriptive phrases
# results = predictor(text=["person with red cloth", "person with blue cloth"])

# # Query with a single concept
# results = predictor(text=["a person"])